'use client';

import React, { useState } from 'react';
import {
  Copy,
  Check,
  Download,
  PlusCircle,
  FileText,
  Sparkles,
  Layers,
  RotateCcw,
} from 'lucide-react';
import { SummarizeResponse } from '@/types/summary';
import { ExtractedDocument, SummaryLength } from '@/types/document';
import { KeyPoints } from './KeyPoints';
import { Badge } from '@/components/ui/Badge';

interface SummaryResultProps {
  document: ExtractedDocument;
  result: SummarizeResponse;
  selectedLength: SummaryLength;
  onUploadAnother: () => void;
  onRegenerate: () => void;
  isRegenerating?: boolean;
}

export function SummaryResult({
  document,
  result,
  selectedLength,
  onUploadAnother,
  onRegenerate,
  isRegenerating = false,
}: SummaryResultProps) {
  const [copiedType, setCopiedType] = useState<'summary' | 'all' | null>(null);

  const handleCopySummary = async () => {
    try {
      await navigator.clipboard.writeText(result.summary);
      setCopiedType('summary');
      setTimeout(() => setCopiedType(null), 2000);
    } catch {
      // Fallback
    }
  };

  const handleCopyAll = async () => {
    try {
      const fullText = `# Summary of ${document.fileName}\n\n## Overview (${selectedLength.toUpperCase()})\n${result.summary}\n\n## Key Takeaways\n${result.keyPoints.map((p) => `- ${p}`).join('\n')}`;
      await navigator.clipboard.writeText(fullText);
      setCopiedType('all');
      setTimeout(() => setCopiedType(null), 2000);
    } catch {
      // Fallback
    }
  };

  const handleDownload = () => {
    const markdownContent = `# Summary: ${document.fileName}
Generated by Document Summary Assistant
Source: ${document.fileName} (${document.wordCount.toLocaleString()} words)
Summary Length: ${selectedLength.toUpperCase()}

## Overview
${result.summary}

## Key Takeaways
${result.keyPoints.map((p) => `- ${p}`).join('\n')}
`;

    const blob = new Blob([markdownContent], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = window.document.createElement('a');
    a.href = url;
    a.download = `${document.fileName.replace(/\.[^/.]+$/, '')}-summary.md`;
    window.document.body.appendChild(a);
    a.click();
    window.document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const compressionPercent = document.wordCount > 0
    ? Math.max(0, Math.round((1 - result.wordCount / document.wordCount) * 100))
    : 0;

  return (
    <article className="paper-panel editorial-reveal w-full p-5 sm:p-8 lg:p-10">
      <div className="flex flex-col justify-between gap-5 border-b-4 border-[var(--ink)] pb-6 sm:flex-row sm:items-end">
        <div>
          <div className="flex items-center gap-3">
            <span className="flex h-8 w-8 items-center justify-center bg-[var(--cobalt)] text-white">
              <Sparkles className="h-4 w-4" strokeWidth={1.5} />
            </span>
            <span className="font-utility text-[10px] uppercase tracking-[0.18em] text-[var(--oxblood)]">Final edit</span>
          </div>
          <h3 className="mt-4 font-editorial text-5xl font-medium leading-none tracking-[-0.035em] sm:text-7xl">
            The brief.
          </h3>
          <p className="mt-3 max-w-md truncate text-xs text-[var(--muted)]">
            Edited from <span className="text-[var(--ink)]">{document.fileName}</span>
          </p>
        </div>

        <div className="flex flex-wrap items-center gap-2">
          <Badge variant="primary">{selectedLength} edit</Badge>
          <Badge variant="default" className="gap-1.5">
            <FileText className="h-3 w-3" />
            {result.wordCount.toLocaleString()} words
          </Badge>
          {compressionPercent > 0 && (
            <Badge variant="success" className="gap-1.5">
              <Layers className="h-3 w-3" />
              {compressionPercent}% shorter
            </Badge>
          )}
          {result.chunksProcessed && result.chunksProcessed > 1 && (
            <Badge variant="secondary">{result.chunksProcessed} sections</Badge>
          )}
        </div>
      </div>

      <section className="py-8 sm:py-10">
        <div className="mb-5 flex items-center justify-between border-b border-[var(--rule)] pb-3">
          <h4 className="font-utility text-[10px] uppercase tracking-[0.18em] text-[var(--oxblood)]">Overview</h4>
          <span className="font-editorial text-lg italic text-[var(--muted)]">Read time: {Math.max(1, Math.ceil(result.wordCount / 200))} min</span>
        </div>
        <div className="max-w-[780px] font-editorial text-xl leading-[1.65] text-[var(--ink)] sm:text-[1.4rem]">
          {result.summary.split('\n\n').map((paragraph, i) => (
            <p key={i} className={`${i === 0 ? 'first-letter:float-left first-letter:mr-2 first-letter:font-editorial first-letter:text-6xl first-letter:font-semibold first-letter:leading-[0.8] first-letter:text-[var(--cobalt)]' : ''} mb-5`}>
              {paragraph}
            </p>
          ))}
        </div>
      </section>

      <section>
        <KeyPoints points={result.keyPoints} />
      </section>

      <div className="mt-8 flex flex-col justify-between gap-5 border-t-4 border-[var(--ink)] pt-5 lg:flex-row lg:items-center">
        <div className="flex flex-wrap items-center gap-x-5 gap-y-3">
          <button
            type="button"
            onClick={handleCopySummary}
            className="inline-flex items-center gap-1.5 border-b border-[var(--ink)] py-1 font-utility text-[9px] uppercase tracking-[0.1em] transition hover:text-[var(--cobalt)]"
          >
            {copiedType === 'summary' ? (
              <>
                <Check className="h-4 w-4 text-[var(--cobalt)]" />
                <span>Brief copied</span>
              </>
            ) : (
              <>
                <Copy className="h-4 w-4" />
                <span>Copy brief</span>
              </>
            )}
          </button>

          <button
            type="button"
            onClick={handleCopyAll}
            className="inline-flex items-center gap-1.5 border-b border-[var(--ink)] py-1 font-utility text-[9px] uppercase tracking-[0.1em] transition hover:text-[var(--cobalt)]"
          >
            {copiedType === 'all' ? (
              <>
                <Check className="h-4 w-4 text-[var(--cobalt)]" />
                <span>Markdown copied</span>
              </>
            ) : (
              <>
                <Copy className="h-4 w-4" />
                <span>Copy markdown</span>
              </>
            )}
          </button>

          <button
            type="button"
            onClick={handleDownload}
            className="inline-flex items-center gap-1.5 border-b border-[var(--ink)] py-1 font-utility text-[9px] uppercase tracking-[0.1em] transition hover:text-[var(--cobalt)]"
          >
            <Download className="h-4 w-4" />
            <span>Download MD</span>
          </button>

          <button
            type="button"
            onClick={onRegenerate}
            disabled={isRegenerating}
            className="inline-flex items-center gap-1.5 border-b border-[var(--ink)] py-1 font-utility text-[9px] uppercase tracking-[0.1em] transition hover:text-[var(--cobalt)] disabled:opacity-50"
          >
            <RotateCcw className={`h-4 w-4 ${isRegenerating ? 'animate-spin' : ''}`} />
            <span>Recompose</span>
          </button>
        </div>

        <button
          type="button"
          onClick={onUploadAnother}
          className="inline-flex items-center justify-center gap-2 bg-[var(--ink)] px-5 py-3 font-utility text-[9px] uppercase tracking-[0.12em] text-white transition hover:bg-[var(--cobalt)]"
        >
          <PlusCircle className="h-4 w-4" />
          <span>Start another brief</span>
        </button>
      </div>
    </article>
  );
}
