'use client';

import React, { useState } from 'react';
import {
  Copy,
  Check,
  Download,
  PlusCircle,
  FileText,
  Sparkles,
  Layers,
  Clock,
  RotateCcw,
} from 'lucide-react';
import { SummarizeResponse } from '@/types/summary';
import { ExtractedDocument, SummaryLength } from '@/types/document';
import { KeyPoints } from './KeyPoints';
import { Badge } from '@/components/ui/Badge';

interface SummaryResultProps {
  document: ExtractedDocument;
  result: SummarizeResponse;
  selectedLength: SummaryLength;
  onUploadAnother: () => void;
  onRegenerate: () => void;
  isRegenerating?: boolean;
}

export function SummaryResult({
  document,
  result,
  selectedLength,
  onUploadAnother,
  onRegenerate,
  isRegenerating = false,
}: SummaryResultProps) {
  const [copiedType, setCopiedType] = useState<'summary' | 'all' | null>(null);

  const handleCopySummary = async () => {
    try {
      await navigator.clipboard.writeText(result.summary);
      setCopiedType('summary');
      setTimeout(() => setCopiedType(null), 2000);
    } catch {
      // Fallback
    }
  };

  const handleCopyAll = async () => {
    try {
      const fullText = `# Summary of ${document.fileName}\n\n## Overview (${selectedLength.toUpperCase()})\n${result.summary}\n\n## Key Takeaways\n${result.keyPoints.map((p) => `- ${p}`).join('\n')}`;
      await navigator.clipboard.writeText(fullText);
      setCopiedType('all');
      setTimeout(() => setCopiedType(null), 2000);
    } catch {
      // Fallback
    }
  };

  const handleDownload = () => {
    const markdownContent = `# Summary: ${document.fileName}
Generated by Document Summary Assistant
Source: ${document.fileName} (${document.wordCount.toLocaleString()} words)
Summary Length: ${selectedLength.toUpperCase()}

## Overview
${result.summary}

## Key Takeaways
${result.keyPoints.map((p) => `- ${p}`).join('\n')}
`;

    const blob = new Blob([markdownContent], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = window.document.createElement('a');
    a.href = url;
    a.download = `${document.fileName.replace(/\.[^/.]+$/, '')}-summary.md`;
    window.document.body.appendChild(a);
    a.click();
    window.document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const compressionPercent = document.wordCount > 0
    ? Math.max(0, Math.round((1 - result.wordCount / document.wordCount) * 100))
    : 0;

  return (
    <div className="w-full rounded-2xl border border-zinc-200 bg-white p-6 sm:p-8 shadow-sm dark:border-zinc-800 dark:bg-zinc-900 space-y-6 animate-in fade-in slide-in-from-bottom-2 duration-300">
      {/* Header & Stats */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-5 border-b border-zinc-100 dark:border-zinc-800">
        <div>
          <div className="flex items-center gap-2">
            <span className="flex h-7 w-7 items-center justify-center rounded-lg bg-blue-100 text-blue-600 dark:bg-blue-950/60 dark:text-blue-400">
              <Sparkles className="h-4 w-4" />
            </span>
            <h3 className="text-lg font-bold text-zinc-900 dark:text-zinc-100">
              Document Summary
            </h3>
            <Badge variant="primary" className="uppercase">
              {selectedLength}
            </Badge>
          </div>
          <p className="mt-1 text-xs text-zinc-500 dark:text-zinc-400">
            Synthesized from <span className="font-medium text-zinc-700 dark:text-zinc-300">{document.fileName}</span>
          </p>
        </div>

        {/* Compression & Metric Badges */}
        <div className="flex flex-wrap items-center gap-2 text-xs">
          <Badge variant="default" className="gap-1">
            <FileText className="h-3 w-3 text-zinc-500" />
            {result.wordCount.toLocaleString()} words generated
          </Badge>
          {compressionPercent > 0 && (
            <Badge variant="success" className="gap-1">
              <Layers className="h-3 w-3 text-emerald-600" />
              {compressionPercent}% condensed
            </Badge>
          )}
          {result.chunksProcessed && result.chunksProcessed > 1 && (
            <Badge variant="secondary">
              {result.chunksProcessed} map-reduce chunks
            </Badge>
          )}
        </div>
      </div>

      {/* Main Prose Summary */}
      <div className="space-y-4">
        <h4 className="text-xs font-semibold uppercase tracking-wider text-zinc-500 dark:text-zinc-400">
          Executive Summary
        </h4>
        <div className="prose prose-zinc dark:prose-invert max-w-none text-sm leading-relaxed text-zinc-800 dark:text-zinc-200">
          {result.summary.split('\n\n').map((paragraph, i) => (
            <p key={i} className="mb-3">
              {paragraph}
            </p>
          ))}
        </div>
      </div>

      {/* Key Takeaways List */}
      <div className="pt-2">
        <KeyPoints points={result.keyPoints} />
      </div>

      {/* Action Bar */}
      <div className="flex flex-wrap items-center justify-between gap-3 pt-5 border-t border-zinc-100 dark:border-zinc-800">
        <div className="flex flex-wrap items-center gap-2">
          {/* Copy Summary */}
          <button
            type="button"
            onClick={handleCopySummary}
            className="inline-flex items-center gap-1.5 rounded-xl border border-zinc-200 bg-white px-3.5 py-2 text-xs font-semibold text-zinc-800 shadow-sm transition hover:bg-zinc-50 active:scale-95 dark:border-zinc-700 dark:bg-zinc-800 dark:text-zinc-200 dark:hover:bg-zinc-700"
          >
            {copiedType === 'summary' ? (
              <>
                <Check className="h-4 w-4 text-emerald-600 dark:text-emerald-400" />
                <span className="text-emerald-600 dark:text-emerald-400">Copied Summary!</span>
              </>
            ) : (
              <>
                <Copy className="h-4 w-4 text-zinc-500" />
                <span>Copy Summary</span>
              </>
            )}
          </button>

          {/* Copy All */}
          <button
            type="button"
            onClick={handleCopyAll}
            className="inline-flex items-center gap-1.5 rounded-xl border border-zinc-200 bg-white px-3.5 py-2 text-xs font-semibold text-zinc-800 shadow-sm transition hover:bg-zinc-50 active:scale-95 dark:border-zinc-700 dark:bg-zinc-800 dark:text-zinc-200 dark:hover:bg-zinc-700"
          >
            {copiedType === 'all' ? (
              <>
                <Check className="h-4 w-4 text-emerald-600 dark:text-emerald-400" />
                <span className="text-emerald-600 dark:text-emerald-400">Copied All!</span>
              </>
            ) : (
              <>
                <Copy className="h-4 w-4 text-zinc-500" />
                <span>Copy All (Markdown)</span>
              </>
            )}
          </button>

          {/* Download */}
          <button
            type="button"
            onClick={handleDownload}
            className="inline-flex items-center gap-1.5 rounded-xl border border-zinc-200 bg-white px-3.5 py-2 text-xs font-semibold text-zinc-800 shadow-sm transition hover:bg-zinc-50 active:scale-95 dark:border-zinc-700 dark:bg-zinc-800 dark:text-zinc-200 dark:hover:bg-zinc-700"
          >
            <Download className="h-4 w-4 text-zinc-500" />
            <span>Download .md</span>
          </button>

          {/* Regenerate */}
          <button
            type="button"
            onClick={onRegenerate}
            disabled={isRegenerating}
            className="inline-flex items-center gap-1.5 rounded-xl border border-zinc-200 bg-white px-3.5 py-2 text-xs font-semibold text-zinc-800 shadow-sm transition hover:bg-zinc-50 active:scale-95 disabled:opacity-50 dark:border-zinc-700 dark:bg-zinc-800 dark:text-zinc-200 dark:hover:bg-zinc-700"
          >
            <RotateCcw className={`h-4 w-4 text-zinc-500 ${isRegenerating ? 'animate-spin' : ''}`} />
            <span>Regenerate</span>
          </button>
        </div>

        {/* Upload Another */}
        <button
          type="button"
          onClick={onUploadAnother}
          className="inline-flex items-center gap-1.5 rounded-xl bg-blue-600 px-4 py-2 text-xs font-semibold text-white shadow-sm shadow-blue-500/20 transition hover:bg-blue-700 active:scale-95 dark:bg-blue-600 dark:hover:bg-blue-500"
        >
          <PlusCircle className="h-4 w-4" />
          <span>Upload Another</span>
        </button>
      </div>
    </div>
  );
}
